name: kinnect
description: AI supported social media app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1

  # GEREKLİ GÜNCELLEME: Hata veren paketi son sürüme çektik
  intl: ^0.20.2

  # İKONLAR
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.6

  # SUPABASE
  supabase_flutter: ^2.8.0

  # GİRİŞ EKRANI
  introduction_screen: ^3.1.14

  # FONTLAR
  google_fonts: ^6.2.1

  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
